# Generated by Django 5.2.13 on 2026-04-16 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                (
                    "dni",
                    models.CharField(
                        help_text="National identity document number.",
                        max_length=20,
                        unique=True,
                        verbose_name="DNI",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email address for the patient.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for the patient.",
                        max_length=30,
                        verbose_name="phone number",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Full postal address of the patient.",
                        verbose_name="address",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal clinical notes about the patient.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive patients are not shown in default listings.",
                        verbose_name="active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "patient",
                "verbose_name_plural": "patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
